---
docker:
  user: ubuntu
  groups:
  - docker
  docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  docker_deps:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - apt-utils

compose:
  setup_compose: true
  compose_basedir: docker
  compose_file_dirs:
  - prometheus
  - prometheus/config
  compose_file:
    composeVersion: "3.7"
    restartPolicy: unless-stopped
    services: {}
