---
- name: "Copy Docker compose file"
  template:
    src: docker-compose.yaml.j2
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/docker-compose.yaml"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0640

- name: "Copy Prometheus config"
  template:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/prometheus/config/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'prometheus.yaml.j2', dest: 'prometheus.yml' }

- name: "Copy Loki config"
  template:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/loki/config/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'loki.yaml.j2', dest: 'loki.yml' }

- name: "Copy Promtail config"
  template:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/promtail/config/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'promtail.yaml.j2', dest: 'promtail.yml' }

- name: "Copy Alertmanager config"
  copy:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/alertmanager/config/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'alertmanager.yml', dest: 'alertmanager.yml' }

- name: "Copy Kubernetes certificate files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/prometheus/config/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'certs/k0s-kubernetes-ca.crt', dest: 'k0s-kubernetes-ca.crt'}
  - { src: 'certs/k0s-kubernetes.crt', dest: 'k0s-kubernetes.crt'}
  - { src: 'certs/k0s-kubernetes.key', dest: 'k0s-kubernetes.key'}
  - { src: 'certs/k8s-kubernetes-ca.crt', dest: 'k8s-kubernetes-ca.crt'}
  - { src: 'certs/k8s-kubernetes.crt', dest: 'k8s-kubernetes.crt'}
  - { src: 'certs/k8s-kubernetes.key', dest: 'k8s-kubernetes.key'}

- name: "Copy Alertmanager rules"
  copy:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/prometheus/config/rules/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'rules/certificates.yml', dest: 'certificates.yml'}
  - { src: 'rules/nginx.yml', dest: 'nginx.yml'}
  - { src: 'rules/promtail.yml', dest: 'promtail.yml'}

- name: "Copy Alertmanager templates"
  copy:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/alertmanager/config/alertmanager_templates/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'alertmanager_templates/slack.tmpl', dest: 'slack.tmpl'}

- name: "Configure Grafana"
  template:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ compose.compose_basedir }}/grafana/config/{{ item.dest }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0644
  with_items:
  - { src: 'grafana.ini.j2', dest: 'grafana.ini' }

- name: "Install pip3"
  package:
    name: python3-pip
    state: latest

- name: "Install Python Docker SDK"
  pip:
    name:
    - docker
    - docker-compose

- name: "Start containers"
  community.docker.docker_compose:
    project_src: "{{ homedir }}/{{ compose.compose_basedir }}/prometheus"
    build: no
    pull: yes
