---
- name: "Ensure {{ docker.user }}"
  user:
    name: "{{ docker.user }}"
    state: present
  register: ensure_user

- set_fact:
    homedir: "{{ ensure_user.home }}"

- name: "Create compose basedir"
  file:
    state: directory
    recurse: no
    path: "{{ homedir }}/{{ compose.compose_basedir }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0755

- name: "Create compose directories"
  file:
    state: directory
    recurse: no
    path: "{{ homedir }}/{{ compose.compose_basedir }}/{{ item }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0755
  with_items:
    - "{{ compose.compose_file_dirs }}"